export const ADD_LOADING_API = 'ADD_LOADING_API';
export const CLEAR_LOADED_API = 'CLEAR_LOADED_API';
export const CLEAR_AUTH_TOKEN = 'CLEAR_AUTH_TOKEN';
export const SIGN_IN = 'SIGN_IN';
export const RESET_PASSWORD = 'RESET_PASSWORD';
